export const mockAdverts = [
  {
    slug: "figura-goku-dragonball",
    title: "Figura Goku Dragon Ball",
    description: "Figura coleccionable de Goku en modo Super Saiyajin.",
    price: 25.00,
    isForSale: true,
    isReserved: false,
    images: ["https://via.placeholder.com/300x300?text=Goku"],
    category: "Dragon Ball",
    subcategory: "Figura",
    state: "Nuevo",
    collection: "Edición Especial 2024",
    manufacturer: "Bandai",
    tags: ["anime", "goku", "figura"],
    author: { username: "coleccionista92", avatar: "https://via.placeholder.com/50x50?text=U1" },
    createdAt: "2024-04-15T12:00:00Z"
  },
  {
    slug: "carta-pokemon-pikachu",
    title: "Carta Pokémon Pikachu 1ra Edición",
    description: "Carta original Pikachu con holograma de la primera edición.",
    price: 120.00,
    isForSale: true,
    isReserved: true,
    images: ["https://via.placeholder.com/300x300?text=Pikachu"],
    category: "Pokémon",
    subcategory: "Carta",
    state: "Usado",
    collection: "Base Set",
    manufacturer: "Nintendo",
    tags: ["pokemon", "pikachu", "carta"],
    author: { username: "pokemonfan", avatar: "https://via.placeholder.com/50x50?text=U2" },
    createdAt: "2024-04-12T09:30:00Z"
  },
  {
    slug: "comic-spiderman-1990",
    title: "Cómic Spiderman 1990",
    description: "Edición original de cómic de Spiderman del año 1990.",
    price: 60.00,
    isForSale: false,
    isReserved: false,
    images: ["https://via.placeholder.com/300x300?text=Spiderman"],
    category: "Marvel",
    subcategory: "Cómic",
    state: "Roto",
    collection: "Clásicos Marvel",
    manufacturer: "Marvel",
    tags: ["comic", "spiderman", "coleccion"],
    author: { username: "marvelcollector", avatar: "https://via.placeholder.com/50x50?text=U3" },
    createdAt: "2024-03-20T10:00:00Z"
  },
  {
    slug: "vinilo-beatles-abbeyroad",
    title: "Vinilo Abbey Road - The Beatles",
    description: "Vinilo original del álbum Abbey Road, edición de 1969.",
    price: 90.00,
    isForSale: true,
    isReserved: false,
    images: ["https://via.placeholder.com/300x300?text=Beatles"],
    category: "Música",
    subcategory: "Vinilo",
    state: "Usado",
    collection: "Vintage Vinyl",
    manufacturer: "EMI",
    tags: ["beatles", "musica", "vinilo"],
    author: { username: "vinilero", avatar: "https://via.placeholder.com/50x50?text=U4" },
    createdAt: "2024-03-10T08:00:00Z"
  },
  {
    slug: "figura-yoda-starwars",
    title: "Figura Yoda Star Wars",
    description: "Figura detallada de Yoda, edición limitada.",
    price: 45.00,
    isForSale: true,
    isReserved: false,
    images: ["https://via.placeholder.com/300x300?text=Yoda"],
    category: "Star Wars",
    subcategory: "Figura",
    state: "Nuevo",
    collection: "Jedi Collection",
    manufacturer: "Hasbro",
    tags: ["starwars", "yoda", "figura"],
    author: { username: "galaxia", avatar: "https://via.placeholder.com/50x50?text=U5" },
    createdAt: "2024-04-01T16:00:00Z"
  },
  {
    slug: "juego-snes-zelda",
    title: "The Legend of Zelda SNES",
    description: "Cartucho original de Zelda para Super Nintendo.",
    price: 75.00,
    isForSale: true,
    isReserved: false,
    images: ["https://via.placeholder.com/300x300?text=Zelda"],
    category: "Videojuegos",
    subcategory: "Cartucho",
    state: "Usado",
    collection: "Retro Games",
    manufacturer: "Nintendo",
    tags: ["zelda", "snes", "retro"],
    author: { username: "retrogamer", avatar: "https://via.placeholder.com/50x50?text=U6" },
    createdAt: "2024-02-20T14:00:00Z"
  },
  {
    slug: "funko-ironman-marvel",
    title: "Funko Pop Iron Man #11",
    description: "Funko Pop de Iron Man en edición metálica.",
    price: 35.00,
    isForSale: true,
    isReserved: false,
    images: ["https://via.placeholder.com/300x300?text=Iron+Man"],
    category: "Marvel",
    subcategory: "Figura",
    state: "Nuevo",
    collection: "Funko Pop Heroes",
    manufacturer: "Funko",
    tags: ["funko", "ironman", "marvel"],
    author: { username: "funkoadicto", avatar: "https://via.placeholder.com/50x50?text=U7" },
    createdAt: "2024-03-05T18:45:00Z"
  },
  {
    slug: "cassette-queen-bohemian",
    title: "Cassette Queen - Bohemian Rhapsody",
    description: "Cassette original de Queen con Bohemian Rhapsody.",
    price: 15.00,
    isForSale: true,
    isReserved: true,
    images: ["https://via.placeholder.com/300x300?text=Queen"],
    category: "Música",
    subcategory: "Cassette",
    state: "Usado",
    collection: "Retro Music",
    manufacturer: "EMI",
    tags: ["queen", "cassette", "bohemian"],
    author: { username: "audiophile", avatar: "https://via.placeholder.com/50x50?text=U8" },
    createdAt: "2024-02-28T12:00:00Z"
  },
  {
    slug: "figura-link-zelda",
    title: "Figura Link Breath of the Wild",
    description: "Figura detallada de Link edición Breath of the Wild.",
    price: 40.00,
    isForSale: true,
    isReserved: false,
    images: ["https://via.placeholder.com/300x300?text=Link"],
    category: "Zelda",
    subcategory: "Figura",
    state: "Nuevo",
    collection: "BOTW Edition",
    manufacturer: "Nintendo",
    tags: ["zelda", "link", "figura"],
    author: { username: "hyrulefan", avatar: "https://via.placeholder.com/50x50?text=U9" },
    createdAt: "2024-04-02T10:00:00Z"
  },
  {
    slug: "carta-yugi-dragonblanco",
    title: "Carta Yugioh Dragón Blanco",
    description: "Carta ultra rara del Dragón Blanco de Ojos Azules.",
    price: 110.00,
    isForSale: false,
    isReserved: false,
    images: ["https://via.placeholder.com/300x300?text=Yugioh"],
    category: "Yu-Gi-Oh",
    subcategory: "Carta",
    state: "Usado",
    collection: "Rare Cards",
    manufacturer: "Konami",
    tags: ["yugioh", "dragon", "carta"],
    author: { username: "kaibafan", avatar: "https://via.placeholder.com/50x50?text=U10" },
    createdAt: "2024-03-30T10:00:00Z"
  }
];
